server:
  port: 8080

spring:
  application:
    name: banco-austro

datasources:
  cuenca:
    url: jdbc:postgresql://localhost:5434/banco_cuenca
    username: banco
    password: banco123
  quito:
    url: jdbc:postgresql://localhost:5433/banco_quito
    username: banco
    password: banco123
